package Speaky_codenameone;


import static com.codename1.ui.CN.*;

import Gui.OfferGuimobile.AfficherOffersGuimobile;
import Gui.OfferGuimobile.AjouterOfferGuimobile;
import Gui.SiteGuimobile.AfficherSitesGuimobile;
import com.codename1.ui.*;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;

import java.io.*;

import com.codename1.ui.layouts.BoxLayout;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form hi = new Form(BoxLayout.y());
        hi.setUIID("form");
        hi.getToolbar().hideToolbar();
        Label label1_l=new Label("Life is best");
        Label label2_l=new Label("when you're");
        Label label3_l=new Label("camping");
        label1_l.setUIID("label1l");
        label2_l.setUIID("label2l");
        label3_l.setUIID("label3l");
        Button Ajouteroffer=new Button("Ajouter votre offre");
        Ajouteroffer.setUIID("Ajouteroffer");
        Button displayoffers=new Button("Informez-vous sur les offres disponibles");
        displayoffers.animate();
        displayoffers.setUIID("displayoffers");
        Button displaysites=new Button("Informez-vous sur les sites camping disponibles");
        displaysites.animate();
        displaysites.setUIID("displaysites");
        Ajouteroffer.addActionListener(e -> new AjouterOfferGuimobile(hi).show());
        displayoffers.addActionListener(e -> new AfficherOffersGuimobile(hi));
        displaysites.addActionListener(e -> {
            try {
                new AfficherSitesGuimobile(hi);
            } catch (IOException ioException) {
                ioException.printStackTrace();
            }
        });
        hi.addAll(label1_l,label2_l,label3_l,Ajouteroffer,displayoffers,displaysites);
        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}
